In [1]:
import pandas as pd
load = pd.read_excel('atus/ehresp_2014.xlsx')
column_names = ['eeincome1', 'erhhch', 'erincome', 'erspemch', 'ertpreat', 'ertseat', 'ethgt', 'etwgt', 'eudietsoda', 'eudrink', 'eueat', 'euexercise', 'euexfreq', 'eufastfd', 'eufastfdfrq', 'euffyday', 'eufdsit', 'eufinlwgt', 'eusnap', 'eugroshp', 'euhgt', 'euinclvl', 'euincome2', 'eumeat', 'eumilk', 'euprpmel', 'eusoda', 'eustores', 'eustreason', 'eutherm', 'euwgt', 'euwic', 'exincome1', 'eugenhth', 'erbmi']
dataset = load[column_names]
print(dataset.shape)

(11212, 35)

In [2]:
dataset = dataset.applymap(lambda x: max(x,0))

In [3]:
class DecisionTreeNode:
    def __init__(self):
        self.col = None
        self.parent = None
        self.value = None
        self.children = []
        self.heritage = []

In [4]:
dataset['erbmi'].std()/dataset['erbmi'].mean()

0.3256685463712994

In [5]:
df = dataset[dataset.erincome == 1]

In [6]:
dataset.columns

Index(['eeincome1', 'erhhch', 'erincome', 'erspemch', 'ertpreat', 'ertseat',
       'ethgt', 'etwgt', 'eudietsoda', 'eudrink', 'eueat', 'euexercise',
       'euexfreq', 'eufastfd', 'eufastfdfrq', 'euffyday', 'eufdsit',
       'eufinlwgt', 'eusnap', 'eugroshp', 'euhgt', 'euinclvl', 'euincome2',
       'eumeat', 'eumilk', 'euprpmel', 'eusoda', 'eustores', 'eustreason',
       'eutherm', 'euwgt', 'euwic', 'exincome1', 'eugenhth', 'erbmi'],
      dtype='object')

In [7]:
for col in dataset:
    print(dataset[col].max())

3
3
5
5
508
990
2
2
3
2
2
2
38
2
21
2
3
103000000.0
2
3
77
6
3
2
2
3
2
5
6
2
340
2
87
5
73.599998

In [8]:
for col in dataset:
    print(dataset.query( str(col) + " == 105"))

Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
       eeincome1  erhhch  erincome  erspemch  ertpreat  ertseat  ethgt  etwgt  \
16             3       3         2         0       105        2      0      0
33             1       3         1         5       105        0      0      0
129            1       3         1         5       105        2      0      0
145            2       3         5         0       105        0      0      0
153            1       3         1         0       105       10      0      0
163            2       1         3         0       105        0      0      0
202            2       3         3         5       105        0      0      0
222            2       3         3         5       105        0      0      0
280            1       3         1         5       105       10      0      0
361            3       3         2         4       105        0      0      0
379            2       3         3         0       105       10      0      0
422            1       3         1         5       105        0      0      0
439            1       3         1         0       105        0      0      0
515            1       3         1         0       105        0      0      0
531            1       3         1         0       105        0      0      0
554            2       3         3         5       105        0      0      0
566            1       3         1         0       105        0      0      0
573            1       3         1         5       105       35      0      0
605            1       1         1         0       105       20      0      0
607            1       3         1         5       105       15      0      0
615            1       3         1         5       105        5      0      0
659            1       3         1         5       105        0      0      0
693            0       3         4         0       105      645      0      0
732            1       3         1         5       105       20      0      0
743            1       3         1         5       105        0      0      0
756            2       3         5         0       105        0      0      0
775            1       3         1         0       105       30      0      0
789            1       3         1         0       105        0      0      0
817            1       3         1         3       105       50      0      0
839            1       3         1         0       105        0      0      0
...          ...     ...       ...       ...       ...      ...    ...    ...
9997           1       3         1         0       105        0      0      0
10041          1       3         1         0       105        0      0      0
10096          1       3         1         5       105       17      0      0
10144          1       3         1         5       105        0      0      0
10151          1       3         1         5       105       15      0      0
10171          1       3         1         5       105        5      0      0
10214          1       3         1         5       105        0      0      0
10226          1       3         1         5       105       20      0      0
10241          1       3         1         0       105        0      0      0
10310          1       3         1         5       105       40      0      0
10349          1       3         1         0       105        0      0      0
10355          3       3         2         5       105        0      0      0
10417          1       3         1         5       105        0      0      0
10423          1       3         1         0       105       10      0      0
10493          1       1         1         5       105       30      0      0
10496          1       3         1         2       105        0      0      0
10513          2       3         5         0       105        0      0      0
10527          1       3         1         5       105        0      0      0
10581          3       3         2         5       105        0      0      0
10725          1       3         1         5       105       90      0      0
10792          2       3         5         0       105        0      0      0
10917          1       3         1         5       105        5      0      0
10942          1       3         1         5       105       10      0      0
10948          2       3         5         0       105        0      0      0
10976          1       3         1         0       105       30      0      0
11016          1       3         1         5       105        0      0      0
11065          2       3         3         3       105        0      0      0
11095          1       3         1         5       105       10      0      0
11110          1       3         1         5       105        3      0      0
11200          2       3         5         5       105        0      0      0

       eudietsoda  eudrink    ...      euprpmel  eusoda  eustores  eustreason  \
16              0        1    ...             1       2         1           2
33              0        2    ...             3       0         1           6
129             2        1    ...             1       1         1           4
145             0        2    ...             1       0         4           2
153             3        1    ...             2       1         2           1
163             0        1    ...             1       2         2           1
202             0        1    ...             2       2         0           0
222             0        2    ...             1       0         1           0
280             0        1    ...             2       2         0           0
361             0        2    ...             1       0         0           0
379             0        1    ...             1       2         2           3
422             0        2    ...             1       0         1           3
439             0        1    ...             1       2         3           1
515             0        2    ...             1       0         1           2
531             2        1    ...             1       1         1           2
554             0        2    ...             1       0         0           0
566             0        2    ...             2       0         0           0
573             0        1    ...             2       2         2           4
605             0        2    ...             2       0         3           3
607             0        1    ...             3       2         1           6
615             0        2    ...             1       0         5           3
659             0        2    ...             1       0         1           1
693             0        1    ...             1       2         0           0
732             0        1    ...             1       2         1           1
743             0        1    ...             2       2         2           2
756             2        1    ...             2       1         1           1
775             2        1    ...             1       1         3           1
789             1        1    ...             1       1         1           2
817             0        2    ...             1       0         1           3
839             0        2    ...             2       0         0           0
...           ...      ...    ...           ...     ...       ...         ...
9997            0        1    ...             1       2         5           2
10041           0        1    ...             1       2         1           1
10096           1        1    ...             3       1         1           3
10144           0        1    ...             1       2         1           2
10151           0        1    ...             3       2         1           5
10171           0        1    ...             1       2         2           1
10214           0        1    ...             1       2         1           1
10226           1        1    ...             3       1         1           4
10241           0        1    ...             1       2         1           3
10310           1        1    ...             3       1         0           0
10349           0        1    ...             1       2         1           4
10355           0        2    ...             1       0         0           0
10417           0        2    ...             1       0         2           1
10423           0        1    ...             1       2         1           1
10493           0        1    ...             3       2         1           3
10496           0        1    ...             3       2         1           1
10513           0        1    ...             1       2         1           1
10527           0        1    ...             1       2         1           2
10581           0        2    ...             2       0         0           0
10725           2        1    ...             1       1         1           1
10792           1        1    ...             2       1         0           0
10917           0        1    ...             1       2         1           3
10942           0        1    ...             1       2         1           6
10948           0        2    ...             1       0         1           2
10976           1        1    ...             3       1         2           6
11016           0        2    ...             1       0         3           2
11065           2        1    ...             1       1         1           1
11095           0        1    ...             3       2         1           2
11110           0        1    ...             2       2         3           4
11200           0        1    ...             1       2         1           4

       eutherm  euwgt  euwic  exincome1  eugenhth      erbmi
16           2    132      0          0         2  25.799999
33           0    189      0          0         2  27.100000
129          1    210      0          0         1  27.700001
145          1    140      0          0         4   0.000000
153          0    172      2          0         2  26.900000
163          2    115      2          0         2  20.400000
202          0    213      0          0         3  37.700001
222          2    180      0          0         4  29.000000
280          0    205      0          0         3  32.099998
361          0    140      0          0         3  26.400000
379          2    285      0          0         3  47.400002
422          2    140      2         72         3  24.000000
439          2    130      0          0         3  20.400000
515          0    200      0          0         2  26.400000
531          2    172      0          0         2  25.400000
554          2    240      2          0         2  31.700001
566          0    216      2         75         4  35.900002
573          0    220      0          0         2  35.500000
605          0    167      2          0         2  27.000000
607          2    125      2          0         1  20.799999
615          2    140      2          0         3  20.700001
659          2    250      2          0         3  44.299999
693          0    125      0          3         5  17.000000
732          2      0      0          0         1   0.000000
743          0    158      2          0         2  27.100000
756          0    230      0          0         2  31.200001
775          2    180      2          0         4  29.000000
789          1    180      0          0         4  25.799999
817          2    112      2          0         1  19.200001
839          0    154      0          0         3  31.100000
...        ...    ...    ...        ...       ...        ...
9997         0      0      0         81         0   0.000000
10041        2    167      0          0         3  28.700001
10096        2    141      2          0         3  22.799999
10144        2    165      2          0         2  25.799999
10151        1    265      2          0         3  39.099998
10171        2    180      0          0         3  27.400000
10214        2    165      2          0         2  25.799999
10226        1    160      2          0         1  22.299999
10241        2    162      2          0         2  29.600000
10310        1    210      2          0         2  27.700001
10349        2    123      0          0         1  21.799999
10355        0    185      1          0         1  30.799999
10417        2    123      0          0         1  21.100000
10423        2    140      0          0         1  24.000000
10493        1    220      0          0         1  30.700001
10496        2    200      0          0         2  28.700001
10513        0    130      0          0         5  23.799999
10527        2    140      2          0         4  25.600000
10581        0    155      0          0         1  23.600000
10725        2    180      0          0         3  29.000000
10792        0    300      0          0         5  41.799999
10917        2    128      2          0         3  22.700001
10942        2    164      2          0         1  26.500000
10948        0    180      0          0         4  30.900000
10976        2    150      0          0         1  25.700001
11016        2      0      0          0         3   0.000000
11065        2    156      2          0         5  29.500000
11095        2    163      2          0         3  27.100000
11110        0    184      2          0         1  25.700001
11200        2    153      0          0         3  26.299999

[288 rows x 35 columns]
       eeincome1  erhhch  erincome  erspemch  ertpreat  ertseat  ethgt  etwgt  \
6589           1       3         1         0       150      105      0      0
6918           0       3         0         0        60      105      0      0
7102           1       3         1         5       195      105      0      0
7390           1       3         1         0        60      105      0      0
8125           1       3         1         5        40      105      0      0
8787           1       3         1         5        20      105      0      0
9388           1       3         1         0        90      105      0      0
10554          1       3         1         0        20      105      0      0
10621          1       1         1         5       140      105      0      0

       eudietsoda  eudrink    ...      euprpmel  eusoda  eustores  eustreason  \
6589            0        1    ...             1       2         1           2
6918            1        1    ...             2       1         2           1
7102            0        1    ...             1       2         0           0
7390            0        1    ...             1       2         1           2
8125            0        2    ...             3       0         1           4
8787            1        1    ...             1       1         2           4
9388            0        1    ...             1       2         1           3
10554           0        2    ...             1       0         1           1
10621           0        1    ...             1       2         1           4

       eutherm  euwgt  euwic  exincome1  eugenhth      erbmi
6589         0    158      0         81         1  24.000000
6918         0      0      0          3         3   0.000000
7102         2    205      2          0         2  25.600000
7390         2    233      2          0         5  42.599998
8125         2    180      2          0         1  25.799999
8787         2    220      0          0         3  41.599998
9388         0    125      0          0         1  21.500000
10554        0    180      2          0         2  31.900000
10621        2    170      0          0         2  29.200001

[9 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame
Columns: [eeincome1, erhhch, erincome, erspemch, ertpreat, ertseat, ethgt, etwgt, eudietsoda, eudrink, eueat, euexercise, euexfreq, eufastfd, eufastfdfrq, euffyday, eufdsit, eufinlwgt, eusnap, eugroshp, euhgt, euinclvl, euincome2, eumeat, eumilk, euprpmel, eusoda, eustores, eustreason, eutherm, euwgt, euwic, exincome1, eugenhth, erbmi]
Index: []

[0 rows x 35 columns]
Empty DataFrame